# Generated by Django 3.1.7 on 2021-09-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
