# Generated by Django 3.1.7 on 2021-09-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0002_auto_20210919_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
